[tool:pytest]
filterwarnings =
    ignore:'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning
    ignore::DeprecationWarning:aiohttp.*
    ignore:coroutine 'AsyncMockMixin._execute_mock_call' was never awaited:RuntimeWarning
    ignore:Enable tracemalloc to get the object allocation traceback:RuntimeWarning
addopts = -W ignore::DeprecationWarning:aiohttp
